[versions]
agp = "8.13.2"
kotlin = "1.9.22"
appcompat = "1.7.1"
activity = "1.12.2"
constraintlayout = "2.2.1"
coil = "2.5.0"
converterGson = "3.0.0"
espressoCore = "3.6.1"
firebaseBom = "34.7.0"
junit = "4.13.2"
junitVersion = "1.2.1"
lifecycleViewmodel = "2.7.0"
loggingInterceptor = "4.12.0"
lottie = "6.1.0"
material = "1.13.0"
recyclerview = "1.3.2"
retrofit = "3.0.0"
viewpager2 = "1.1.0"
googleGms = "4.4.1"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleGms" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
